trigger:
- main
 
pool:
  name: Jobsystem-Agent
 
stages:
- stage: BuildAndTest
  displayName: Build and Test HTTP Container
 
  jobs:
  - job: DockerTest
    displayName: Docker Build + Run
    steps:
    
    - checkout: self
 
    - script: |
        echo "Building image..."
        docker build -t pipeline-http-test .
 
      displayName: Build Image
 
    - script: |
        echo "Running container..."
        docker run -d -p 8080:80 --name http-test pipeline-http-test
        sleep 5
        curl http://localhost:8080
      displayName: Run and Test Container
 
    - script: |
        docker rm -f http-test || true
      displayName: Cleanup
