trigger:
- main
 
pool:
  name: Jobsystem-Agent
 
stages:
- stage: BuildAndTest
  displayName: Build and Test HTTP Container
 
  jobs:
  - job: DockerTest
    displayName: Docker Build + Run
    steps:
    
    - checkout: self
 
    - script: |
        echo "Building backend image..."
        docker build -t pipeline-backend-test ./hello-world-devops/backend
      displayName: Build Backend Image
 
    - script: |
        echo "Building frontend image..."
        docker build -t pipeline-frontend-test ./hello-world-devops/frontend
      displayName: Build Frontend Image
 
    - script: |
        echo "Running backend container..."
        docker run -d -p 8080:8080 --name backend-test pipeline-backend-test
        sleep 10
        docker logs backend-test
        docker ps -a | grep backend-test
        curl http://localhost:8080 || echo "Curl failed, but continuing..."
      displayName: Run and Test Backend

    - script: |
        echo "Running frontend container..."
        docker run -d -p 3000:80 --name frontend-test pipeline-frontend-test
        sleep 5
        curl http://localhost:3000
      displayName: Run and Test Frontend
 
    - script: |
        docker rm -f backend-test || true
        docker rm -f frontend-test || true
      displayName: Cleanup
